---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.MultusValidatingWebhookName}}
  labels:
    app: multus-admission-controller
{{- if not .HyperShiftEnabled}}
# Webhook cannot use the injected CA bundle in hypershift since the endpoint runs in the management cluster
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
{{- end }}
webhooks:
  - name: multus-validating-config.k8s.io
    clientConfig:
{{- if .HyperShiftEnabled}}
      url: "https://multus-admission-controller.{{.AdmissionControllerNamespace}}.svc/validate"
      caBundle: {{.ManagementServiceCABundle}}
{{ else }}
      service:
        name: multus-admission-controller
        namespace: {{.AdmissionControllerNamespace}}
        path: "/validate"
{{- end }}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["k8s.cni.cncf.io"]
        apiVersions: ["v1"]
        resources: ["network-attachment-definitions"]
    matchConditions:
      # On updates, only validate if the Spec changes
      - name: CreateDeleteOrUpdatedSpec
        expression: oldObject == null || object == null || has(object.spec) != has(oldObject.spec) || (has(object.spec) && object.spec != oldObject.spec)
{{if .OVN_PRE_CONF_UDN_ADDR_ENABLE}}
      # Ignore default/openshift-ovn-kubernetes NAD to avoid a race between ovn-kubernetes and the multus webhook on install
      - name: IgnoreDefaultOVNKubernetesNAD
        expression: object == null || object.metadata.namespace != "openshift-ovn-kubernetes" || object.metadata.name != "default"
{{- end }}
    sideEffects: NoneOnDryRun
    admissionReviewVersions:
    - v1
    timeoutSeconds: 30
