---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frr-k8s-daemon
  namespace: openshift-frr-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-frr-k8s
  namespace: openshift-frr-k8s
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-frr-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - frr-k8s-validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - update
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - bgpsessionstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - bgpsessionstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrnodestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrnodestates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-frr-k8s
  namespace: openshift-frr-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-frr-k8s
subjects:
- kind: ServiceAccount
  name: frr-k8s-daemon
  namespace: openshift-frr-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-frr-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-frr-k8s
subjects:
- kind: ServiceAccount
  name: frr-k8s-daemon
  namespace: openshift-frr-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: openshift-frr-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: frr-k8s-daemon
  namespace: openshift-frr-k8s
